# Change these first
owner: shindouj # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: SearXNG
    url: https://search.jeikobu.net
  - name: Redlib (for Reddit)
    url: https://redlib.jeikobu.net
  - name: Quetre (for Quora)
    url: https://quetre.jeikobu.net
  - name: LibremDB (for IMDB)
    url: https://libremdb.jeikobu.net
  - name: Dumb (for Genius)
    url: https://dumb.jeikobu.net
  - name: Mozhi (translation services)
    url: https://mozhi.jeikobu.net
  - name: Rimgo (for Imgur)
    url: https://rimgo.jeikobu.net
  - name: OpenTogetherTube
    url: https://watchtogether.jeikobu.net
  - name: Chihiro Paste
    url: https://p.chihi.ro
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jeikobu.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Current service status for **jeikobu.net**"
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime). Contact owner in case of an outage.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Owner
      href: https://jeikobu.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
